export { Cart } from "./Cart/Cart";
export { Home } from "./Home/Home";
export { PageNotFound } from "./PageNotFound";
export { ULogin } from "./User/UserLogin.jsx";
export { URegis } from "./User/UserRegister.jsx";
export { UProfile } from "./User/UserProfile.jsx";
export { Product } from "./Product";
export { Payment } from "./Payment/Payment.jsx";
export { VerifyEmail } from "./User/VerifyEmail.jsx";